#!/usr/bin/env python3
"""
Run quality checks in parallel and output structured JSON.

Runs pyright, pyrefly, mypy, ruff, ast-grep, semgrep, and importlinter concurrently
and aggregates results by file.
"""

import argparse
import asyncio
import json
import os
import re
import subprocess
import sys
import tomllib
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class Error:
    """A single error from a quality tool."""

    file: str
    line: int | None
    code: str
    message: str
    tool: str
    severity: str = "error"


@dataclass
class ToolResult:
    """Result from running a single tool."""

    tool: str
    success: bool
    errors: list[Error] = field(default_factory=list)
    stdout: str = ""
    stderr: str = ""
    exit_code: int = 0


@dataclass
class QualityReport:
    """Aggregated quality check report."""

    verdict: str  # "PASS" or "FAIL"
    total_errors: int
    errors_by_file: dict[str, list[Error]] = field(default_factory=dict)
    errors_by_tool: dict[str, list[Error]] = field(default_factory=dict)
    tool_results: list[ToolResult] = field(default_factory=list)


def extract_excludes_from_pyproject() -> list[str]:
    """Extract exclude patterns from pyproject.toml as union of all tool excludes."""
    pyproject_path = Path.cwd() / "pyproject.toml"
    if not pyproject_path.exists():
        return []

    with open(pyproject_path, "rb") as f:
        config = tomllib.load(f)

    all_excludes: set[str] = set()

    # Get ruff extend-exclude patterns
    ruff_excludes = config.get("tool", {}).get("ruff", {}).get("extend-exclude", [])
    if ruff_excludes:
        all_excludes.update(ruff_excludes)
        print(f"Found {len(ruff_excludes)} ruff excludes", file=sys.stderr)

    # Get pyright exclude patterns
    pyright_excludes = config.get("tool", {}).get("pyright", {}).get("exclude", [])
    if pyright_excludes:
        all_excludes.update(pyright_excludes)
        print(f"Found {len(pyright_excludes)} pyright excludes", file=sys.stderr)

    # If no exclusions found, return empty list
    if not all_excludes:
        return []

    print(f"Union: {len(all_excludes)} total excludes", file=sys.stderr)
    return sorted(all_excludes)  # Return sorted list for deterministic output


def generate_ast_grep_config(excludes: list[str]) -> None:
    """Generate .ast-grep/sgconfig.yml from exclude patterns."""
    ast_grep_dir = Path.cwd() / ".ast-grep"
    if not ast_grep_dir.exists():
        return

    sgconfig_path = ast_grep_dir / "sgconfig.yml"

    # Build the config content
    config_lines = [
        "ruleDirs:",
        "  - rules",
        "languageGlobs:",
        "  python:",
        '    - "**/*.py"',
        "    # Exclusions from pyproject.toml (auto-generated)",
    ]

    # Add negation patterns for each exclude
    for exclude in excludes:
        # Convert to negation pattern
        if not exclude.startswith("!"):
            # If pattern doesn't already end with /** and doesn't have a file extension,
            # add /** to match directory contents
            if not exclude.endswith("/**") and "**" not in exclude and "*." not in exclude:
                # This looks like a directory pattern
                if exclude.endswith("/"):
                    pattern = f"{exclude}**"
                else:
                    pattern = f"{exclude}/**"
            else:
                pattern = exclude
            config_lines.append(f'    - "!{pattern}"')

    config_lines.append("")  # Trailing newline

    # Write the config file
    sgconfig_path.write_text("\n".join(config_lines))
    print(f"Generated {sgconfig_path} with {len(excludes)} exclusions", file=sys.stderr)


def generate_semgrep_ignore(excludes: list[str]) -> Path:
    """Generate temporary .semgrepignore file from exclude patterns."""
    semgrepignore_path = Path.cwd() / ".semgrepignore"

    # Build the ignore file content
    ignore_lines = [
        "# Auto-generated from pyproject.toml - DO NOT EDIT",
        "# This file is regenerated by run-quality-checks.py",
        "",
    ]

    # Add each exclude pattern
    for exclude in excludes:
        # semgrep uses gitignore-style patterns
        ignore_lines.append(exclude)

    ignore_lines.append("")  # Trailing newline

    # Write the ignore file
    semgrepignore_path.write_text("\n".join(ignore_lines))
    print(f"Generated {semgrepignore_path} with {len(excludes)} exclusions", file=sys.stderr)

    return semgrepignore_path


async def run_command(cmd: list[str], cwd: Path | None = None) -> tuple[str, str, int]:
    """Run command asynchronously and return (stdout, stderr, exit_code)."""
    process = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        cwd=cwd,
    )
    stdout_bytes, stderr_bytes = await process.communicate()
    stdout = stdout_bytes.decode("utf-8", errors="replace")
    stderr = stderr_bytes.decode("utf-8", errors="replace")
    return stdout, stderr, process.returncode or 0


def parse_pyright_output(output: str) -> list[Error]:
    """Parse pyright JSON output into Error objects."""
    errors = []
    try:
        data = json.loads(output)
        # Pyright JSON structure: {"generalDiagnostics": [...], ...}
        for diagnostic in data.get("generalDiagnostics", []):
            errors.append(
                Error(
                    file=diagnostic.get("file", ""),
                    line=diagnostic.get("range", {}).get("start", {}).get("line", 0) + 1,  # Pyright uses 0-indexed lines
                    code=diagnostic.get("rule", "unknown"),
                    message=diagnostic.get("message", ""),
                    tool="pyright",
                    severity=diagnostic.get("severity", "error"),
                )
            )
    except (json.JSONDecodeError, KeyError, TypeError):
        # Fallback to text parsing if JSON parsing fails
        pattern = r"^(.+?):(\d+):(\d+)\s*-\s*(error|warning):\s*(.+?)(?:\s*\[([^\]]+)\])?$"
        for line in output.splitlines():
            match = re.match(pattern, line.strip())
            if match:
                file_path, line_no, _, severity, message, code = match.groups()
                errors.append(
                    Error(
                        file=file_path,
                        line=int(line_no),
                        code=code or "unknown",
                        message=message.strip(),
                        tool="pyright",
                        severity=severity,
                    )
                )
    return errors


def parse_pyrefly_output(output: str) -> list[Error]:
    """Parse pyrefly JSON output into Error objects."""
    errors = []
    try:
        data = json.loads(output)
        # Pyrefly uses same JSON structure as pyright
        for diagnostic in data.get("generalDiagnostics", []):
            errors.append(
                Error(
                    file=diagnostic.get("file", ""),
                    line=diagnostic.get("range", {}).get("start", {}).get("line", 0) + 1,
                    code=diagnostic.get("rule", "unknown"),
                    message=diagnostic.get("message", ""),
                    tool="pyrefly",
                    severity=diagnostic.get("severity", "error"),
                )
            )
    except (json.JSONDecodeError, KeyError, TypeError):
        # Fallback to text parsing if JSON parsing fails
        pattern = r"^(.+?):(\d+):(\d+)\s*-\s*(error|warning):\s*(.+?)(?:\s*\[([^\]]+)\])?$"
        for line in output.splitlines():
            match = re.match(pattern, line.strip())
            if match:
                file_path, line_no, _, severity, message, code = match.groups()
                errors.append(
                    Error(
                        file=file_path,
                        line=int(line_no),
                        code=code or "unknown",
                        message=message.strip(),
                        tool="pyrefly",
                        severity=severity,
                    )
                )
    return errors


def parse_mypy_output(output: str) -> list[Error]:
    """Parse mypy output into Error objects."""
    errors = []
    # Mypy text format: file.py:line:column: severity: message [error-code]
    # Example: src/foo.py:10:5: error: Incompatible return type [return-value]
    pattern = r"^(.+?):(\d+):(\d+):\s*(error|warning|note):\s*(.+?)(?:\s*\[([^\]]+)\])?$"
    for line in output.splitlines():
        match = re.match(pattern, line.strip())
        if match:
            file_path, line_no, _, severity, message, code = match.groups()
            # Skip notes, only report errors and warnings
            if severity in ("error", "warning"):
                errors.append(
                    Error(
                        file=file_path,
                        line=int(line_no),
                        code=code or "unknown",
                        message=message.strip(),
                        tool="mypy",
                        severity=severity,
                    )
                )
    return errors


def parse_ruff_output(output: str) -> list[Error]:
    """Parse ruff JSON output into Error objects."""
    errors = []
    try:
        data = json.loads(output)
        # Ruff JSON is an array of violation objects
        if isinstance(data, list):
            for item in data:
                errors.append(
                    Error(
                        file=item.get("filename", ""),
                        line=item.get("location", {}).get("row", 0),
                        code=item.get("code", "unknown"),
                        message=item.get("message", ""),
                        tool="ruff",
                    )
                )
    except (json.JSONDecodeError, KeyError, TypeError):
        # Fallback to text parsing if JSON parsing fails
        pattern = r"^(.+?):(\d+):(\d+):\s*([A-Z]\d+)\s+(.+)$"
        for line in output.splitlines():
            match = re.match(pattern, line.strip())
            if match:
                file_path, line_no, _, code, message = match.groups()
                errors.append(
                    Error(
                        file=file_path,
                        line=int(line_no),
                        code=code,
                        message=message.strip(),
                        tool="ruff",
                    )
                )
    return errors


def parse_ast_grep_output(output: str) -> list[Error]:
    """Parse ast-grep output into Error objects."""
    errors = []
    # ast-grep outputs JSON array with structure:
    # [{"ruleId": "...", "severity": "...", "file": "...", "message": "...", "range": {...}, ...}]
    try:
        data = json.loads(output)
        if isinstance(data, list):
            for item in data:
                errors.append(
                    Error(
                        file=item.get("file", ""),
                        line=item.get("range", {}).get("start", {}).get("line", 0),
                        code=item.get("ruleId", "ast-grep"),
                        message=item.get("message", ""),
                        tool="ast-grep",
                        severity=item.get("severity", "error"),
                    )
                )
    except (json.JSONDecodeError, KeyError, TypeError):
        # Fallback to text parsing
        for line in output.splitlines():
            if ":" in line:
                parts = line.split(":", 3)
                if len(parts) >= 3:
                    errors.append(
                        Error(
                            file=parts[0],
                            line=int(parts[1]) if parts[1].isdigit() else None,
                            code="ast-grep",
                            message=parts[2] if len(parts) > 2 else line,
                            tool="ast-grep",
                        )
                    )
    return errors


def parse_semgrep_output(output: str) -> list[Error]:
    """Parse semgrep output into Error objects."""
    errors = []
    try:
        data = json.loads(output)
        results = data.get("results", [])
        for result in results:
            errors.append(
                Error(
                    file=result.get("path", ""),
                    line=result.get("start", {}).get("line"),
                    code=result["check_id"],
                    message=result.get("extra", {}).get("message", ""),
                    tool="semgrep",
                    severity=result.get("extra", {}).get("severity", "error"),
                )
            )
    except (json.JSONDecodeError, KeyError):
        # Fallback to text parsing if JSON fails
        pass
    return errors


def parse_importlinter_output(output: str) -> list[Error]:
    """Parse import-linter output into Error objects."""
    errors = []
    # import-linter shows contract violations
    # Format varies, look for common patterns
    current_contract = ""
    for line in output.splitlines():
        if "Contract" in line and "BROKEN" in line:
            current_contract = line.strip()
        elif "->" in line and current_contract:
            # This is likely a violation
            errors.append(
                Error(
                    file="",  # import-linter doesn't give file:line
                    line=None,
                    code="import-linter",
                    message=f"{current_contract}: {line.strip()}",
                    tool="import-linter",
                )
            )
    return errors


async def run_pyright(module_path: Path) -> ToolResult:
    """Run pyright on module.

    Note: pyright must be run without explicit paths to respect exclude patterns.
    When explicit paths are passed, excludes are ignored. We run it once for the
    whole project using pyproject.toml configuration.
    """
    # Run pyright with NO path arguments - uses include/exclude from pyproject.toml
    # Passing explicit paths overrides exclude configuration
    cmd = ["uv", "run", "pyright", "--outputjson"]

    stdout, stderr, exit_code = await run_command(cmd)

    errors = parse_pyright_output(stdout) + parse_pyright_output(stderr)

    return ToolResult(
        tool="pyright",
        success=exit_code == 0,
        errors=errors,
        stdout=stdout,
        stderr=stderr,
        exit_code=exit_code,
    )


async def run_pyrefly(module_path: Path) -> ToolResult:
    """Run pyrefly on module.

    Note: pyrefly must be run without explicit paths to respect exclude patterns.
    When explicit paths are passed, excludes are ignored. We run it once for the
    whole project using pyproject.toml configuration.
    """
    # Run pyrefly with NO path arguments - uses include/exclude from pyproject.toml
    # Passing explicit paths overrides exclude configuration
    cmd = ["uv", "run", "pyrefly", "--outputjson"]

    stdout, stderr, exit_code = await run_command(cmd)

    errors = parse_pyrefly_output(stdout) + parse_pyrefly_output(stderr)

    return ToolResult(
        tool="pyrefly",
        success=exit_code == 0,
        errors=errors,
        stdout=stdout,
        stderr=stderr,
        exit_code=exit_code,
    )


async def run_mypy(module_path: Path) -> ToolResult:
    """Run mypy on module.

    Note: mypy must be run without explicit paths to respect exclude patterns.
    When explicit paths are passed, excludes are ignored. We run it once for the
    whole project using pyproject.toml configuration.
    """
    # Run mypy with NO path arguments - uses exclude from pyproject.toml
    # Passing explicit paths overrides exclude configuration
    cmd = ["uv", "run", "mypy"]

    stdout, stderr, exit_code = await run_command(cmd)

    errors = parse_mypy_output(stdout) + parse_mypy_output(stderr)

    return ToolResult(
        tool="mypy",
        success=exit_code == 0,
        errors=errors,
        stdout=stdout,
        stderr=stderr,
        exit_code=exit_code,
    )


async def run_ruff(module_path: Path) -> ToolResult:
    """Run ruff on module."""
    # Add --force-exclude to respect extend-exclude even for explicit paths
    # Also add explicit --extend-exclude for tests to ensure they're skipped
    cmd = [
        "uv", "run", "ruff", "check",
        "--force-exclude",
        "--extend-exclude", "**/tests/**",
        "--output-format", "json",
        str(module_path)
    ]
    stdout, stderr, exit_code = await run_command(cmd)

    errors = parse_ruff_output(stdout) + parse_ruff_output(stderr)

    return ToolResult(
        tool="ruff",
        success=exit_code == 0,
        errors=errors,
        stdout=stdout,
        stderr=stderr,
        exit_code=exit_code,
    )


async def run_ast_grep(module_path: Path) -> ToolResult:
    """Run ast-grep on module."""
    # Run ast-grep with rules from .ast-grep directory
    ast_grep_dir = Path.cwd() / ".ast-grep"
    if not ast_grep_dir.exists():
        return ToolResult(tool="ast-grep", success=True, errors=[])

    cmd = ["ast-grep", "scan", "--json", str(module_path)]
    stdout, stderr, exit_code = await run_command(cmd)

    errors = parse_ast_grep_output(stdout)

    return ToolResult(
        tool="ast-grep",
        success=len(errors) == 0,
        errors=errors,
        stdout=stdout,
        stderr=stderr,
        exit_code=exit_code,
    )


async def run_semgrep(module_path: Path) -> ToolResult:
    """Run semgrep on module."""
    cmd = ["uv", "run", "semgrep", "scan", "--config=auto", "--json", str(module_path)]

    # Create subprocess with environment variables for proxy
    process = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        env={
            **os.environ,
            "CUSTOM_CERT_BUNDLE_PATH": "/Users/Shared/ca_certs/bundle.pem",
            "HTTP_PROXY": "http://localhost:3128",
            "HTTPS_PROXY": "http://localhost:3128",
        },
    )
    stdout_bytes, stderr_bytes = await process.communicate()
    stdout = stdout_bytes.decode("utf-8", errors="replace")
    stderr = stderr_bytes.decode("utf-8", errors="replace")
    exit_code = process.returncode or 0

    errors = parse_semgrep_output(stdout)

    # Semgrep exit codes: 0 = no findings, 1 = findings found, 2+ = error
    # Success means semgrep ran (exit 0 or 1), not whether it found issues
    return ToolResult(
        tool="semgrep",
        success=exit_code in (0, 1),
        errors=errors,
        stdout=stdout,
        stderr=stderr,
        exit_code=exit_code,
    )


async def run_importlinter() -> ToolResult:
    """Run import-linter on entire project."""
    cmd = ["uv", "run", "lint-imports"]
    stdout, stderr, exit_code = await run_command(cmd)

    errors = parse_importlinter_output(stdout) + parse_importlinter_output(stderr)

    return ToolResult(
        tool="import-linter",
        success=exit_code == 0,
        errors=errors,
        stdout=stdout,
        stderr=stderr,
        exit_code=exit_code,
    )


async def run_all_checks(module_path: Path) -> list[ToolResult]:
    """Run all quality checks in parallel (excluding import-linter, pyright, and pyrefly which run project-wide)."""
    results = await asyncio.gather(
        run_ruff(module_path),
        run_ast_grep(module_path),
        run_semgrep(module_path),
        return_exceptions=True,
    )

    # Filter out exceptions and convert to ToolResult
    tool_results = []
    for result in results:
        if isinstance(result, Exception):
            print(f"Tool execution failed: {result}", file=sys.stderr)
            continue
        if isinstance(result, ToolResult):
            tool_results.append(result)

    return tool_results


def aggregate_errors(tool_results: list[ToolResult]) -> QualityReport:
    """Aggregate errors from all tools by file and by tool."""
    errors_by_file: dict[str, list[Error]] = defaultdict(list)
    errors_by_tool: dict[str, list[Error]] = defaultdict(list)
    total_errors = 0

    for tool_result in tool_results:
        for error in tool_result.errors:
            total_errors += 1
            if error.file:
                errors_by_file[error.file].append(error)
            errors_by_tool[error.tool].append(error)

    verdict = "PASS" if total_errors == 0 else "FAIL"

    return QualityReport(
        verdict=verdict,
        total_errors=total_errors,
        errors_by_file=dict(errors_by_file),
        errors_by_tool=dict(errors_by_tool),
        tool_results=tool_results,
    )


def report_to_dict(report: QualityReport) -> dict[str, Any]:
    """Convert QualityReport to JSON-serializable dict."""
    return {
        "verdict": report.verdict,
        "total_errors": report.total_errors,
        "errors_by_file": {
            file: [
                {
                    "line": err.line,
                    "code": err.code,
                    "message": err.message,
                    "tool": err.tool,
                    "severity": err.severity,
                }
                for err in errors
            ]
            for file, errors in sorted(report.errors_by_file.items())
        },
        "errors_by_tool": {
            tool: [
                {
                    "file": err.file,
                    "line": err.line,
                    "code": err.code,
                    "message": err.message,
                    "severity": err.severity,
                }
                for err in errors
            ]
            for tool, errors in report.errors_by_tool.items()
        },
        "tool_results": [
            {
                "tool": result.tool,
                "success": result.success,
                "error_count": len(result.errors),
                "exit_code": result.exit_code,
            }
            for result in report.tool_results
        ],
    }


def report_to_dict_blind(report: QualityReport) -> dict[str, Any]:
    """Convert QualityReport to blind JSON format (aggregated by tool and error type, no file paths)."""
    # Aggregate error types by tool
    errors_by_tool_and_type: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))

    for tool_result in report.tool_results:
        for error in tool_result.errors:
            # Use error code as the type identifier
            error_type = error.code if error.code else "unknown"
            errors_by_tool_and_type[error.tool][error_type] += 1

    return {
        "verdict": report.verdict,
        "total_errors": report.total_errors,
        "errors_by_tool": {
            tool: dict(error_types)
            for tool, error_types in sorted(errors_by_tool_and_type.items())
        },
    }


def find_module_root(path: Path) -> Path:
    """Find the top-level module root for a given file or directory.

    Walks up the directory tree to find a directory containing pyproject.toml,
    then returns the src/ subdirectory if it exists, otherwise the directory itself.
    """
    current = path if path.is_dir() else path.parent

    # Walk up until we find pyproject.toml
    while current != current.parent:
        if (current / "pyproject.toml").exists():
            # Check if src/ subdirectory exists
            src_dir = current / "src"
            if src_dir.exists() and src_dir.is_dir():
                return src_dir
            return current
        current = current.parent

    # If no pyproject.toml found, return the original path
    return path if path.is_dir() else path.parent


def find_unique_module_roots(paths: list[Path]) -> set[Path]:
    """Find unique top-level module roots for all provided paths."""
    roots = set()
    for path in paths:
        if not path.exists():
            print(f"Warning: Path does not exist: {path}", file=sys.stderr)
            continue
        root = find_module_root(path)
        roots.add(root.resolve())
    return roots


async def run_checks_for_module(module_path: Path) -> tuple[Path, list[ToolResult]]:
    """Run all quality checks for a single module."""
    print(f"Running quality checks on: {module_path}", file=sys.stderr)
    tool_results = await run_all_checks(module_path)
    return module_path, tool_results


async def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Run quality checks on Python modules",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Accepts files or directories. Determines module roots automatically.",
    )
    parser.add_argument(
        "paths",
        nargs="+",
        type=Path,
        help="Files or directories to check",
    )
    parser.add_argument(
        "-o",
        "--output-dir",
        type=Path,
        help="Directory to write JSON output file (in addition to stdout)",
    )
    parser.add_argument(
        "--blind",
        action="store_true",
        help="Blind mode: aggregate errors by tool and error type only, without file paths",
    )

    args = parser.parse_args()

    # Generate config files from pyproject.toml excludes
    excludes = extract_excludes_from_pyproject()
    generate_ast_grep_config(excludes)
    semgrepignore_path = generate_semgrep_ignore(excludes)

    # Find unique module roots
    module_roots = find_unique_module_roots(args.paths)

    if not module_roots:
        print("Error: No valid module roots found", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(module_roots)} unique module(s) to check", file=sys.stderr)

    # Run checks in parallel for all modules
    results = await asyncio.gather(
        *[run_checks_for_module(root) for root in sorted(module_roots)],
        return_exceptions=True
    )

    # Aggregate results from all modules
    all_tool_results = []
    for result in results:
        if isinstance(result, Exception):
            print(f"Module check failed: {result}", file=sys.stderr)
            continue
        _, tool_results = result
        all_tool_results.extend(tool_results)

    # Run pyright once on project-wide (not per-module)
    # Pyright must run without explicit paths to respect exclude patterns
    print("Running pyright on project", file=sys.stderr)
    try:
        pyright_result = await run_pyright(Path("."))  # Path ignored, just for signature
        all_tool_results.append(pyright_result)
    except Exception as e:
        print(f"Pyright execution failed: {e}", file=sys.stderr)

    # Run pyrefly once on project-wide (not per-module)
    # Pyrefly must run without explicit paths to respect exclude patterns
    print("Running pyrefly on project", file=sys.stderr)
    try:
        pyrefly_result = await run_pyrefly(Path("."))  # Path ignored, just for signature
        all_tool_results.append(pyrefly_result)
    except Exception as e:
        print(f"Pyrefly execution failed: {e}", file=sys.stderr)

    # Run mypy once on project-wide (not per-module)
    # Mypy must run without explicit paths to respect exclude patterns
    print("Running mypy on project", file=sys.stderr)
    try:
        mypy_result = await run_mypy(Path("."))  # Path ignored, just for signature
        all_tool_results.append(mypy_result)
    except Exception as e:
        print(f"Mypy execution failed: {e}", file=sys.stderr)

    # Run import-linter once on project-wide (not per-module)
    print("Running import-linter on project", file=sys.stderr)
    try:
        importlinter_result = await run_importlinter()
        all_tool_results.append(importlinter_result)
    except Exception as e:
        print(f"Import-linter execution failed: {e}", file=sys.stderr)

    # Aggregate errors across all modules
    report = aggregate_errors(all_tool_results)

    # Convert to JSON (blind mode or full mode)
    if args.blind:
        output = report_to_dict_blind(report)
    else:
        output = report_to_dict(report)

    json_output = json.dumps(output, indent=2)

    # Output to stdout
    print(json_output)

    # Optionally write to output directory
    if args.output_dir:
        args.output_dir.mkdir(parents=True, exist_ok=True)
        output_file = args.output_dir / "quality-check-results.json"
        output_file.write_text(json_output)
        print(f"Results written to: {output_file}", file=sys.stderr)

    # Cleanup generated files
    try:
        if semgrepignore_path.exists():
            semgrepignore_path.unlink()
            print(f"Cleaned up {semgrepignore_path}", file=sys.stderr)
    except Exception as e:
        print(f"Warning: Failed to cleanup {semgrepignore_path}: {e}", file=sys.stderr)

    # Exit with non-zero if any errors found
    sys.exit(0 if report.verdict == "PASS" else 1)


if __name__ == "__main__":
    asyncio.run(main())
